version: "3"

services:

  capteur_reel:
    build:
      context: ./capteur_reel
    devices:
      - "/dev/ttyACM0"
    volumes:
      -  ./capteur_reel:/app
    environment:
      - PORT_ARDUINO=/dev/ttyACM0
      - AGREGAT_API_SERVER=http://agregat:5000
    depends_on:
      - agregat

  capteur_virtuel:
    build:
      context: ./capteur_virtuel
    volumes:
      - ./capteur_virtuel:/app
    environment:
      - AGREGAT_API_SERVER=http://agregat:5000
    depends_on:
      - agregat

  agregat:
    build:
      context: ./agregat
    volumes:
      - ./agregat:/app

  slot:
    build:
      context: ./slot
    ports:
      - 5000:5000
    volumes:
      - ./slot:/app
    environment:
      - AGREGAT_API_SERVER=http://agregat:5000